name: Optimum neuron / Test INF2

on:
  push:
    branches: [ main ]
    paths:
      - "optimum/**.py"
  pull_request:
    branches: [ main ]
    #paths:
    #  - "optimum/**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  do-the-job:
    name: Run INF2 tests
    runs-on: [self-hosted, 1-aws-inf2, 32-cpu, ci] # run the job on the newly created runner
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Re-install neuronx driver
        run: |
          sudo apt remove aws-neuronx-dkms -y
          sudo apt remove aws-neuronx-tools -y
          . /etc/os-release
          sudo tee /etc/apt/sources.list.d/neuron.list > /dev/null <<EOF
          deb https://apt.repos.neuron.amazonaws.com ${VERSION_CODENAME} main
          EOF
          wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | sudo apt-key add -
          sudo apt-get update -y
          sudo apt-get install linux-headers-$(uname -r) -y
          sudo apt-get install aws-neuronx-dkms=2.* -y
          sudo apt-get install aws-neuronx-tools=2.* -y
          sudo apt-get install aws-neuronx-collectives=2.* -y
          sudo apt-get install aws-neuronx-runtime-lib=2.* -y
          export PATH=/opt/aws/neuron/bin:$PATH
      - name: Install python dependencies
        run: |
          sudo apt install python3.8-venv -y
          python3 -m venv aws_neuron_venv_pytorch 
          source aws_neuron_venv_pytorch/bin/activate
          python -m pip install -U pip
          python -m pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
          python -m pip install .[neuronx,tests]
      - name: Run tests
        run: |
          source aws_neuron_venv_pytorch/bin/activate
          HF_TOKEN_OPTIMUM_NEURON_CI=${{ secrets.HF_TOKEN_OPTIMUM_NEURON_CI }} pytest -m is_inferentia_test tests
 
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
